export const experienceData = [
  {
    id: 1,
    role: "Software Developer",
    company: "TechnoBrains",
    location: "Ahmedabad, Gujarat, India",
    period: "02/2026 – Present",
    type: "Full-Time",
    highlight: "Designing and deploying scalable web applications, RESTful APIs, and cloud services.",
    points: [
      "Designing and developing high-performance web applications and APIs using ASP.NET Core, C#, and SQL Server.",
      "Optimizing database performance with efficient queries, stored procedures, and Entity Framework Core.",
      "Building responsive frontend components and integrating secure backend services.",
    ],
    tech: ["ASP.NET Core", "C#", "SQL Server", "REST API", "React", "Azure"],
  },
  {
    id: 2,
    role: "Software Developer",
    company: "CAA National (Canadian Automobile Association)",
    location: "Ottawa, ON, Canada",
    period: "01/2024 – 02/2026",
    type: "Full-Time",
    highlight: "Architected real-time CAA membership validation APIs, OAuth 2.0 authentication wrapper, and Shopify extensions.",
    points: [
      "Designed and developed secure, scalable RESTful & GraphQL APIs using ASP.NET Core & Azure to validate CAA partner memberships in real time.",
      "Engineered centralized OAuth 2.0 authentication wrapper service utilizing Microsoft Identity Platform for secure API communications.",
      "Created custom Shopify rewards integration extension enabling real-time membership validation during checkout.",
      "Migrated enterprise Umbraco CMS from v13 to v17, implementing TypeScript, Vite, and custom Backoffice extensions.",
      "Built partner onboarding portal using .NET Core and jQuery/AJAX with server-side pagination using DataTable Library.",
      "Managed Azure DevOps CI/CD pipelines, release management, code reviews, and automated deployment processes.",
    ],
    tech: ["ASP.NET Core", "C#", "Azure Cloud", "OAuth 2.0", "GraphQL", "React", "TypeScript", "Vite", "Umbraco CMS", "MS SQL", "Azure DevOps"],
  },
  {
    id: 3,
    role: "Computer Programming (Post-Graduate Diploma)",
    company: "Conestoga College",
    location: "Kitchener, ON, Canada",
    period: "09/2020 – 04/2022",
    type: "Education",
    highlight: "Post-Graduate Diploma focused on advanced object-oriented programming, web development, and software architecture.",
    points: [
      "Specialized in C#, ASP.NET, Java, database design, and web application architecture.",
      "Graduated with honors, demonstrating excellence in software development methodologies and team projects.",
    ],
    tech: ["C#", "ASP.NET", "SQL Server", "JavaScript", "Software Architecture"],
  },
  {
    id: 4,
    role: "Bachelor of IT Engineering",
    company: "Gujarat Technological University",
    location: "Ahmedabad, Gujarat, India",
    period: "08/2015 – 05/2019",
    type: "Education",
    highlight: "Bachelor's degree in Information Technology Engineering.",
    points: [
      "Core foundation in computer science, data structures, algorithms, database management, and web technologies.",
    ],
    tech: ["IT Engineering", "Data Structures", "DBMS", "OOP", "Web Technologies"],
  },
];

export const enterpriseProjects = [
  {
    id: 1,
    title: "CAA Membership Validation APIs",
    company: "CAA National (Canada)",
    desc: "Designed & developed secure, scalable RESTful & GraphQL APIs using ASP.NET Core and Azure to enable CAA partners to validate customer memberships in real time and automate discount eligibility during transaction processing.",
    architecture: "ASP.NET Core Web API + Azure App Services + Azure SQL + Azure Storage",
    tags: ["ASP.NET Core", "C#", "Azure Cloud", "REST API", "GraphQL", "OAuth 2.0"],
  },
  {
    id: 2,
    title: "Centralized OAuth 2.0 Authentication Wrapper",
    company: "CAA National (Canada)",
    desc: "Engineered a centralized OAuth 2.0 authentication wrapper service utilizing Microsoft Identity Platform to standardize secure communication across internal microservices and Microsoft-protected enterprise resources.",
    architecture: "Microsoft Identity Platform + Bearer Tokens + OAuth 2.0 + Microservices",
    tags: ["C#", ".NET Core", "OAuth 2.0", "Azure AD / Entra ID", "Security"],
  },
  {
    id: 3,
    title: "Shopify CAA Rewards Checkout App",
    company: "CAA National (Canada)",
    desc: "Created a custom Shopify integration extension using React Router and checkout extensions to perform real-time CAA membership validation during Shopify checkout and collect transaction data seamlessly.",
    architecture: "Shopify Extension + React Router + Node / .NET Web API Backend",
    tags: ["React", "React Router", "TypeScript", "Shopify API", "Web APIs"],
  },
  {
    id: 4,
    title: "Umbraco Enterprise CMS Web Platform",
    company: "CAA National (Canada)",
    desc: "Maintained and modernised content-driven web application using Umbraco CMS framework in .NET 10. Successfully migrated platform from Umbraco v13 to v17 with TypeScript, Vite, and custom Backoffice extensions.",
    architecture: "Umbraco CMS (.NET 10) + TypeScript + Vite + Azure App Services",
    tags: [".NET 10", "Umbraco CMS", "TypeScript", "Vite", "Azure"],
  },
  {
    id: 5,
    title: "Partner Onboarding & Workflow Portal",
    company: "CAA National (Canada)",
    desc: "Developed a partner onboarding portal using .NET Core backend and jQuery/AJAX frontend with validation workflows, server-side pagination with DataTable Library, and optimized SQL Server stored procedures.",
    architecture: ".NET Core MVC + MS SQL Server + jQuery AJAX + DataTable Library",
    tags: [".NET Core", "SQL Server", "jQuery", "AJAX", "Bootstrap"],
  },
];